services:
  - type: web
    name: dso101-backend
    image:
      url: docker.io/tshewang7/dso101-backend:latest
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: DB_PATH
        value: /app/data/todos.db
      - key: NODE_ENV
        value: production

  - type: web
    name: dso101-frontend
    image:
      url: docker.io/tshewang7/dso101-frontend:latest
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: VITE_API_URL
        value: https://dso101-backend.onrender.com
      - key: REACT_APP_API_URL
        value: https://dso101-backend.onrender.com
