services:
  - type: web
    name: todo-backend-test
    image:
      url: tshewang7/todo-backend:v1.2
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: DB_PATH
        value: /app/data/todos.db
      - key: NODE_ENV
        value: production

  - type: web
    name: todo-frontend-test
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: VITE_API_URL
        value: https://todo-backend-test-0srz.onrender.com
      - key: REACT_APP_API_URL
        value: https://todo-backend-test-0srz.onrender.com
