services:
  - type: web
    name: todo-backend-test
    dockerCommand: docker run -p 5000:5000 -e PORT=5000 -e DB_PATH=/app/data/todos.db -e NODE_ENV=production tshewang7/dso101-backend:latest
    plan: free

  - type: web
    name: todo-frontend-test
    dockerCommand: docker run -p 3000:3000 -e PORT=3000 -e VITE_API_URL=https://todo-backend-test-0srz.onrender.com -e REACT_APP_API_URL=https://todo-backend-test-0srz.onrender.com tshewang7/dso101-frontend:latest
    plan: free
